SET SCHEMA 'customerdb';

INSERT INTO "CUSTOMER"("NAME") VALUES('Rajiv Saxena');
INSERT INTO "CUSTOMER"("NAME") VALUES('Sameer Meher');
INSERT INTO "CUSTOMER"("NAME") VALUES('Tushar Dixit');
INSERT INTO "CUSTOMER"("NAME") VALUES('Ravi Ahuja');
INSERT INTO "CUSTOMER"("NAME") VALUES('Ram Kumar');